# Generated by Django 5.2.9 on 2026-01-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_followup_prescription_treatmentplan_treatmentsession_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentplan',
            old_name='estimated_duration_days',
            new_name='estimated_duration_months',
        ),
    ]
