# Generated by Django 5.2.9 on 2026-01-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_estimated_duration_days_treatmentplan_estimated_duration_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentsession',
            name='appointment',
        ),
    ]
