# Generated by Django 5.2.10 on 2026-01-09 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_treatmentsession_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_availibility', models.DateTimeField()),
                ('end_time_availibility', models.DateTimeField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('app', 'App')], db_index=True, default='app', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
