# Generated by Django 5.2.10 on 2026-01-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointmentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='end_time_availibility',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='start_time_availibility',
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='day_availability',
            field=models.DateField(blank=True, null=True),
        ),
    ]
