# Generated by Django 5.2.10 on 2026-01-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
