# Generated by Django 5.2.10 on 2026-01-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_remove_appointmentrequest_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('card', 'Debit Card/ Credit Card'), ('bank_transfer', 'Bank Transfer(NEFT/IMPS)'), ('cash', 'Cash')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
