# Generated by Django 5.2.10 on 2026-01-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_appointment_payment_method_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
