# Generated by Django 5.2.9 on 2026-01-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-issued_at']},
        ),
    ]
