# Generated by Django 5.2.10 on 2026-01-18 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_delete_prescription'),
        ('prescriptions', '0003_prescription_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='treatment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='appointments.treatmentplan'),
        ),
    ]
