# Generated by Django 5.2.10 on 2026-01-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_medicine_prescriptionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='time_of_day',
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='afternoon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='duration_days',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='evening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='morning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='before_after_food',
            field=models.CharField(choices=[('before', 'Before Food'), ('after', 'After Food')], max_length=12),
        ),
    ]
