# Generated by Django 5.2.10 on 2026-01-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_remove_medicine_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
